import {
  Ambulance,
  Baby,
  Briefcase,
  Building2,
  ClipboardCheck,
  Droplets,
  FileText,
  Flame,
  Gavel,
  GraduationCap,
  HardHat,
  HeartHandshake,
  House,
  Landmark,
  Leaf,
  Lightbulb,
  Map as MapIcon,
  Megaphone,
  Phone,
  Receipt,
  Scale,
  ScrollText,
  ShieldCheck,
  Siren,
  Store,
  Trash2,
  TreePine,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/types";

const ICONS: Record<IconName, LucideIcon> = {
  ambulance: Ambulance,
  baby: Baby,
  briefcase: Briefcase,
  building: Building2,
  clipboard: ClipboardCheck,
  droplets: Droplets,
  file: FileText,
  flame: Flame,
  gavel: Gavel,
  graduation: GraduationCap,
  hardhat: HardHat,
  heart: HeartHandshake,
  home: House,
  landmark: Landmark,
  leaf: Leaf,
  lightbulb: Lightbulb,
  map: MapIcon,
  megaphone: Megaphone,
  phone: Phone,
  receipt: Receipt,
  scale: Scale,
  scroll: ScrollText,
  shield: ShieldCheck,
  siren: Siren,
  store: Store,
  trash: Trash2,
  tree: TreePine,
  users: Users,
  wallet: Wallet,
  zap: Zap,
};

/** Renders an icon from the data files by its string key. */
export function Icon({ name, className }: { name: IconName; className?: string }) {
  const Cmp = ICONS[name] ?? FileText;
  return <Cmp className={className} aria-hidden="true" strokeWidth={1.6} />;
}
